// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Emilia: typeof import('./src/components/ui/Emilia.vue')['default']
    Phone: typeof import('./src/components/ui/Phone.vue')['default']
    Task2Grid: typeof import('./src/components/Task2Grid.vue')['default']
    Task5Card: typeof import('./src/components/Task5Card.vue')['default']
    Toggle: typeof import('./src/components/ui/Toggle.vue')['default']
  }
}

export { }
