// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Counter: typeof import('./src/components/Counter.vue')['default']
    Emilia: typeof import('./src/components/Emilia.vue')['default']
    GridSolution: typeof import('./src/components/GridSolution.vue')['default']
    Phone: typeof import('./src/components/Phone.vue')['default']
    Task2Grid: typeof import('./src/components/Task2Grid.vue')['default']
    Task4MobileContent: typeof import('./src/components/Task4MobileContent.vue')['default']
    Task5Card: typeof import('./src/components/Task5Card.vue')['default']
    Toggle: typeof import('./src/components/Toggle.vue')['default']
  }
}

export { }
