// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Artwork: typeof import('./src/components/Artwork.vue')['default']
    ContactDetail: typeof import('./src/components/ContactDetail.vue')['default']
    ContactList: typeof import('./src/components/ContactList.vue')['default']
    Melli: typeof import('./src/components/ui/Melli.vue')['default']
    NavBar: typeof import('./src/components/NavBar.vue')['default']
    Note: typeof import('./src/components/Note.vue')['default']
    Phone: typeof import('./src/components/ui/Phone.vue')['default']
    Toggle: typeof import('./src/components/ui/Toggle.vue')['default']
  }
}

export { }
